apiVersion: v1
kind: Pod
metadata:
  name: nginx-env
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: URL
          value: google.com




    #apiVersion: v1	Standard template version
    #kind: Pod	Create a Pod
    #name: nginx-env	Pod's name
    #containers: - name: nginx	One container, named nginx
    #image: nginx	Uses the nginx image
    #env:	List of environment variables to set inside the container
    #- name: URL	Variable name = URL
  #value: google.com	Variable value = google.com